version: "3.7"
services:
  backend:
    build: .
    depends_on:
      - redis
      - postgres
      - mongo
    links:
      - mongo
      - postgres
      - redis
     post:
      - 3333:80
  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: Apolo
      POSTGRES_PASSWORD: AZ49hd6i!!
      POSTGRES_DB: petshop
    volumes:
      - db-data:/var/lib/postgresql/data
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mitred
      MONGO_INITDB_ROOT_PASSWORD: AZ49hd7i!!
volumes:
  db-data:
